// Code generated by cmd/cgo; DO NOT EDIT.

//line D:\go\data\huiyan\learning_demo\4 interal\go_use_c.go:1:1
package main

//int sum(int a,int b){return a+b;}
import _ "unsafe"

func main() {
	println(( /*line :7:10*/_Cfunc_sum /*line :7:14*/)(2, 2))
}
